// Words that make poor "Mute similar..." suggestions: English function words, common verbs, adjectives and adverbs,
// and headline filler (best, top, apps, alternatives, guide, review, tips, today, news, ...). One list, lower-case,
// compared case-insensitively. Only words of four or more letters are ever offered, so shorter entries are harmless.
// The list is English only; text in other languages relies on the length, digit and script rules in similar.ts.

const WORDS: string[] = [
  "about", "above", "absolutely", "according", "across", "actually", "after", "again", "against", "ahead", "all",
  "along", "already", "also", "alternative", "alternatives", "although", "always", "amid", "among", "and", "announce",
  "announced", "announcement", "announces", "announcing", "annual", "another", "any", "anyone", "anything", "app",
  "apparently", "apps", "are", "aren't", "around", "ask", "asked", "asking", "asks", "away", "back", "backs", "basic",
  "basically", "basics", "because", "become", "becomes", "been", "before", "began", "begin", "beginner", "beginners",
  "begins", "begun", "behind", "being", "below", "beside", "besides", "best", "better", "between", "beyond", "big",
  "both", "brand", "breaking", "bring", "brings", "brought", "but", "call", "called", "calls", "came", "can", "can't",
  "cannot", "case", "cases", "certain", "cheap", "cheaper", "cheapest", "come", "comes", "coming", "complete",
  "completely", "continue", "continued", "continues", "could", "couldn't", "course", "daily", "day", "days", "deal",
  "deals", "definitely", "definitive", "did", "didn't", "discount", "discounts", "does", "doesn't", "doing", "don't",
  "done", "down", "during", "each", "easy", "either", "else", "enough", "entirely", "essential", "essentially",
  "even", "evening", "ever", "every", "everyone", "everything", "except", "exclusive", "exclusively", "explain",
  "explained", "explainer", "explaining", "explains", "extremely", "face", "fact", "fall", "false", "far", "fast",
  "faster", "fastest", "felt", "few", "finally", "find", "finding", "finds", "first", "five", "follow", "following",
  "for", "form", "found", "four", "free", "from", "full", "further", "gave", "generally", "get", "gets", "getting",
  "give", "given", "gives", "goes", "going", "gone", "good", "got", "gotten", "great", "group", "groups", "guide",
  "guides", "guys", "hack", "hacks", "had", "hadn't", "half", "hand", "happen", "happens", "hard", "has", "hasn't",
  "have", "haven't", "having", "help", "helped", "helping", "helps", "her", "here", "here's", "hers", "herself",
  "high", "him", "himself", "his", "hold", "home", "hours", "how", "how's", "however", "hundred", "i'm", "i've",
  "important", "incredibly", "inside", "instead", "into", "introduce", "introduces", "introducing", "isn't", "it's",
  "its", "itself", "just", "keep", "keeps", "kept", "kind", "knew", "know", "known", "knows", "large", "larger",
  "last", "later", "latest", "launch", "launched", "launches", "launching", "learn", "learned", "learning", "learns",
  "least", "leave", "leaves", "left", "less", "let", "let's", "lets", "like", "liked", "likely", "list", "listicle",
  "lists", "literally", "little", "live", "long", "longer", "look", "looked", "looking", "looks", "made", "mainly",
  "make", "makes", "making", "many", "matter", "may", "maybe", "mean", "means", "meant", "meet", "meets", "merely",
  "met", "might", "mind", "month", "monthly", "months", "more", "morning", "most", "mostly", "move", "moved", "moves",
  "moving", "much", "must", "myself", "near", "nearly", "need", "needed", "needs", "never", "new", "newest", "news",
  "next", "night", "nobody", "none", "nor", "not", "nothing", "now", "nowhere", "number", "numbers", "off", "offer",
  "offers", "officially", "often", "old", "once", "one", "ones", "only", "onto", "open", "other", "others", "ought",
  "our", "ours", "ourselves", "out", "outside", "over", "overall", "own", "paid", "part", "parts", "past", "people",
  "per", "perhaps", "pick", "picked", "picking", "picks", "place", "places", "play", "played", "playing", "plays",
  "point", "points", "possible", "possibly", "preview", "previews", "price", "priced", "prices", "probably", "put",
  "puts", "quick", "quite", "ran", "rather", "really", "release", "released", "releases", "releasing", "report",
  "reported", "reportedly", "reporting", "reports", "review", "reviewed", "reviews", "right", "room", "roundup",
  "run", "running", "runs", "said", "sale", "sales", "same", "save", "saves", "saving", "saw", "say", "says",
  "season", "seasons", "second", "see", "seem", "seemed", "seems", "seen", "set", "sets", "setting", "seven",
  "several", "shall", "she", "should", "shouldn't", "show", "showed", "showing", "shown", "shows", "side", "sides",
  "simple", "simply", "since", "single", "six", "small", "smaller", "some", "someone", "something", "sometimes",
  "somewhere", "soon", "start", "started", "starting", "starts", "still", "stop", "stopped", "stopping", "stops",
  "stream", "streaming", "such", "sure", "take", "taken", "takes", "taking", "tell", "telling", "tells", "ten",
  "than", "thank", "that", "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's",
  "therefore", "these", "they", "they're", "they've", "thing", "things", "think", "thinks", "this", "those", "though",
  "thought", "three", "through", "thus", "time", "times", "tips", "today", "together", "told", "tomorrow", "tonight",
  "too", "took", "top", "tops", "totally", "toward", "towards", "tricks", "tried", "tries", "truly", "try", "trying",
  "turn", "turns", "twice", "two", "ultimate", "under", "unless", "until", "unveil", "unveils", "update", "updated",
  "updates", "updating", "upon", "use", "used", "uses", "using", "usually", "versus", "very", "via", "video",
  "videos", "vs", "want", "wanted", "wants", "was", "wasn't", "watch", "watched", "watching", "way", "ways", "we're",
  "we've", "week", "weekend", "weekly", "weeks", "well", "went", "were", "weren't", "what", "what's", "whatever",
  "when", "whenever", "where", "whether", "which", "while", "whilst", "who", "who's", "whole", "whom", "whose", "why",
  "why's", "will", "with", "within", "without", "won't", "wont", "work", "works", "world", "worth", "would",
  "wouldn't", "write", "writes", "written", "wrote", "year", "yearly", "years", "yes", "yesterday", "yet", "you",
  "you'll", "you're", "you've", "young", "your", "yours", "yourself", "yourselves",
];

export const STOP_WORDS: ReadonlySet<string> = new Set(WORDS);

/** The list as written, for tests (lower-case, no repeats). */
export const STOP_WORD_LIST: readonly string[] = WORDS;
