package store

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// SettingSavedSearches is library.saved_searches: the sidebar's saved searches (backend plan F4),
// a JSON array of at most MaxSavedSearches SavedSearch objects. The dedicated endpoints
// /api/saved-searches manage it with read-modify-write inside one write transaction, so two tabs
// never lose each other's edit; PATCH /api/settings may replace the whole list.
const SettingSavedSearches = "library.saved_searches"

// Saved search limits.
const (
	MaxSavedSearches   = 100
	MaxSavedSearchName = 60  // runes
	MaxSavedSearchQ    = 300 // bytes
)

// Saved search views a scope may pin (the unread count is always of unread articles).
var savedSearchViews = map[string]bool{"all": true, "unread": true, "starred": true}

// Saved search orders (GET /api/items ?order=).
var savedSearchOrders = map[string]bool{"date": true, "oldest": true, "rank": true}

// SavedSearchScope narrows a saved search. At most one field is set: a feed, a folder (ids are
// decimal strings) or a view.
type SavedSearchScope struct {
	FeedID   string `json:"feed_id,omitempty"`
	FolderID string `json:"folder_id,omitempty"`
	View     string `json:"view,omitempty"`
}

// SavedSearch is one entry of the setting. ID is server-generated by POST /api/saved-searches.
type SavedSearch struct {
	ID    string            `json:"id"`
	Name  string            `json:"name"`
	Q     string            `json:"q"`
	Scope *SavedSearchScope `json:"scope,omitempty"`
	Order string            `json:"order,omitempty"`
}

// ErrSavedSearchNotFound is returned for an unknown id.
var ErrSavedSearchNotFound = errors.New("store: no such saved search")

// ErrTooManySavedSearches is returned when a create would pass MaxSavedSearches.
var ErrTooManySavedSearches = errors.New("store: too many saved searches")

// DuplicateSavedSearchError is returned when a create repeats a saved search the list already holds: Name is the
// existing entry's name.
type DuplicateSavedSearchError struct{ Name string }

func (e *DuplicateSavedSearchError) Error() string { return "store: already saved as " + e.Name }

// Same reports whether two normalized entries run the same search: same text, scope and order (no order is the
// default, newest first). The name and id do not matter; they do not change what the search finds.
func (s SavedSearch) Same(o SavedSearch) bool {
	ord := func(v string) string {
		if v == "" {
			return "date"
		}
		return v
	}
	if s.Q != o.Q || ord(s.Order) != ord(o.Order) {
		return false
	}
	if s.Scope == nil || o.Scope == nil {
		return s.Scope == nil && o.Scope == nil
	}
	return *s.Scope == *o.Scope
}

// SavedSearchError is a validation failure of one field.
type SavedSearchError struct{ Field, Message string }

func (e *SavedSearchError) Error() string { return e.Field + ": " + e.Message }

func badSS(field, msg string) error { return &SavedSearchError{field, msg} }

// NewSavedSearchID makes an id: "s" and 12 random hex digits.
func NewSavedSearchID() string {
	var b [6]byte
	_, _ = rand.Read(b[:])
	return "s" + hex.EncodeToString(b[:])
}

func validSavedSearchID(id string) bool {
	if id == "" || len(id) > 32 {
		return false
	}
	for i := 0; i < len(id); i++ {
		c := id[i]
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '-' || c == '_') {
			return false
		}
	}
	return true
}

// hasCtl reports a control or line-break character: any Unicode Cc (C0, DEL and the C1 range,
// which includes U+0085 NEL, so a tab too) or the line and paragraph separators U+2028 and U+2029.
func hasCtl(s string) bool {
	for _, r := range s {
		if unicode.Is(unicode.Cc, r) || r == '\u2028' || r == '\u2029' {
			return true
		}
	}
	return false
}

// Normalize checks one entry and returns it in canonical form (trimmed text, canonical scope ids).
// The id is not checked here: creation makes one.
func (s SavedSearch) Normalize() (SavedSearch, error) {
	s.Name = strings.TrimSpace(s.Name)
	s.Q = strings.TrimSpace(s.Q)
	switch {
	case s.Name == "" || utf8.RuneCountInString(s.Name) > MaxSavedSearchName || hasCtl(s.Name):
		return s, badSS("name", fmt.Sprintf("must be 1 to %d characters without line breaks", MaxSavedSearchName))
	case s.Q == "" || len(s.Q) > MaxSavedSearchQ || hasCtl(s.Q):
		return s, badSS("q", fmt.Sprintf("must be a search of 1 to %d bytes without line breaks", MaxSavedSearchQ))
	case s.Order != "" && !savedSearchOrders[s.Order]:
		return s, badSS("order", `must be "date", "oldest" or "rank"`)
	}
	if sc := s.Scope; sc != nil {
		n := 0
		if sc.FeedID != "" {
			n++
			id, ok := NormalizeFavoriteID(sc.FeedID)
			if !ok {
				return s, badSS("scope.feed_id", "must be a feed id")
			}
			sc.FeedID = id
		}
		if sc.FolderID != "" {
			n++
			id, ok := NormalizeFavoriteID(sc.FolderID)
			if !ok {
				return s, badSS("scope.folder_id", "must be a folder id")
			}
			sc.FolderID = id
		}
		if sc.View != "" {
			n++
			if !savedSearchViews[sc.View] {
				return s, badSS("scope.view", `must be "all", "unread" or "starred"`)
			}
		}
		if n != 1 {
			return s, badSS("scope", "must have exactly one of feed_id, folder_id or view (omit scope for the whole library)")
		}
	}
	return s, nil
}

// NormalizeSavedSearches validates a whole list (the settings PATCH path): every entry, ids present,
// well formed and unique, at most MaxSavedSearches.
func NormalizeSavedSearches(list []SavedSearch) ([]SavedSearch, error) {
	if len(list) > MaxSavedSearches {
		return nil, badSS("saved_searches", fmt.Sprintf("at most %d", MaxSavedSearches))
	}
	out := make([]SavedSearch, 0, len(list))
	seen := make(map[string]bool, len(list))
	for _, s := range list {
		if !validSavedSearchID(s.ID) || seen[s.ID] {
			return nil, badSS("id", "must be a unique id of at most 32 letters, digits, - or _")
		}
		seen[s.ID] = true
		n, err := s.Normalize()
		if err != nil {
			return nil, err
		}
		out = append(out, n)
	}
	return out, nil
}

func decodeSavedSearches(raw string) []SavedSearch {
	var list []SavedSearch
	if json.Unmarshal([]byte(raw), &list) != nil {
		return nil
	}
	return list
}

// SavedSearches lists the stored saved searches (a malformed stored value reads as none).
func (d *DB) SavedSearches(ctx context.Context) ([]SavedSearch, error) {
	var raw string
	err := d.reader.QueryRowContext(ctx, "SELECT value FROM settings WHERE key = ?", SettingSavedSearches).Scan(&raw)
	if errors.Is(err, sql.ErrNoRows) {
		return []SavedSearch{}, nil
	}
	if err != nil {
		return nil, err
	}
	list := decodeSavedSearches(raw)
	if list == nil {
		list = []SavedSearch{}
	}
	return list, nil
}

// EditSavedSearches is one atomic read-modify-write of the setting: fn gets the stored list and
// returns the new one, which is validated (NormalizeSavedSearches) and stored, all in one write
// transaction. An error from fn, or a validation error, writes nothing.
func (d *DB) EditSavedSearches(ctx context.Context, fn func([]SavedSearch) ([]SavedSearch, error)) ([]SavedSearch, error) {
	var out []SavedSearch
	err := d.WithWrite(ctx, func(ctx context.Context, tx *sql.Tx) error {
		var raw string
		err := tx.QueryRowContext(ctx, "SELECT value FROM settings WHERE key = ?", SettingSavedSearches).Scan(&raw)
		if err != nil && !errors.Is(err, sql.ErrNoRows) {
			return err
		}
		prev := decodeSavedSearches(raw)
		next, err := fn(append([]SavedSearch(nil), prev...))
		if err != nil {
			return err
		}
		if next, err = NormalizeSavedSearches(next); err != nil {
			return err
		}
		if err := checkNewSavedSearchScopes(ctx, tx, prev, next); err != nil {
			return err
		}
		b, err := json.Marshal(next)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO settings (key, value) VALUES (?, ?)
			ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = unixepoch()`, SettingSavedSearches, string(b)); err != nil {
			return err
		}
		out = next
		return nil
	})
	return out, err
}

// checkNewSavedSearchScopes checks, inside the writing transaction, that every scope of next that
// is new or changed against prev names a feed or folder that exists. It runs in the same
// transaction that stores the list, and a feed or folder delete drops the scopes naming it in its
// own transaction (dropSavedSearchScope), so a scope can never be stored for a row that is already
// gone. A scope left as it was is not checked: an old dangling one must not block other edits.
func checkNewSavedSearchScopes(ctx context.Context, tx *sql.Tx, prev, next []SavedSearch) error {
	before := make(map[string]SavedSearchScope, len(prev))
	for _, p := range prev {
		if p.Scope != nil {
			before[p.ID] = *p.Scope
		}
	}
	for _, n := range next {
		sc := n.Scope
		if sc == nil || (sc.FeedID == "" && sc.FolderID == "") {
			continue
		}
		if old, ok := before[n.ID]; ok && old == *sc {
			continue
		}
		table, id := "feeds", sc.FeedID
		if sc.FeedID == "" {
			table, id = "folders", sc.FolderID
		}
		var exists bool
		if err := tx.QueryRowContext(ctx, "SELECT EXISTS(SELECT 1 FROM "+table+" WHERE id = ?)", id).Scan(&exists); err != nil {
			return err
		}
		if !exists {
			return badSS("scope", "no such feed or folder")
		}
	}
	return nil
}

// dropSavedSearchScope removes the scope of every saved search that names a deleted (or merged
// away) folder or feed, inside the deleting transaction: the search stays, over the whole library,
// rather than pointing at an id that no longer exists. A missing or unreadable row is left alone.
func dropSavedSearchScope(ctx context.Context, tx *sql.Tx, kind string, id int64) error {
	var raw string
	if err := tx.QueryRowContext(ctx, "SELECT value FROM settings WHERE key = ?", SettingSavedSearches).Scan(&raw); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}
		return err
	}
	list := decodeSavedSearches(raw)
	want := strconv.FormatInt(id, 10)
	changed := false
	for i := range list {
		sc := list[i].Scope
		if sc == nil {
			continue
		}
		have := sc.FolderID
		if kind == FavFeed {
			have = sc.FeedID
		}
		if n, ok := NormalizeFavoriteID(have); ok && n == want {
			list[i].Scope = nil
			changed = true
		}
	}
	if !changed {
		return nil
	}
	b, err := json.Marshal(list)
	if err != nil {
		return err
	}
	_, err = tx.ExecContext(ctx, "UPDATE settings SET value = ?, updated_at = unixepoch() WHERE key = ?", string(b), SettingSavedSearches)
	return err
}
