#!/usr/bin/env node
// Regenerates THIRD_PARTY_NOTICES.md. Run at each release, from the repo root,
// after `cd web && npm ci`:   node scripts/gen-notices.mjs
// Needs Go on PATH (module cache populated) and web/node_modules installed.
// Prints any license it cannot classify, or that looks copyleft/non-commercial, to stderr.
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const flagged = [];

function detect(text, declared) {
  const t = text.toLowerCase();
  if (t.includes('apache license') && t.includes('version 2.0')) return 'Apache-2.0';
  if (t.includes('mozilla public license')) return 'MPL-2.0';
  if (t.includes('gnu affero')) return 'AGPL';
  if (t.includes('gnu lesser general')) return 'LGPL';
  if (t.includes('gnu general public')) return 'GPL';
  if (t.includes('mozilla public license')) return 'MPL-2.0';
  if (t.includes('sil open font license')) return 'OFL-1.1';
  if (t.includes('permission is hereby granted, free of charge')) return 'MIT';
  if (t.includes('permission to use, copy, modify, and/or distribute') || t.includes('permission to use, copy, modify, and distribute')) return 'ISC';
  if (t.includes('redistribution and use in source and binary forms')) {
    return t.includes('neither the name') || t.includes('endorse or promote') ? 'BSD-3-Clause' : 'BSD-2-Clause';
  }
  if (t.includes('this is free and unencumbered software')) return 'Unlicense';
  return declared || 'UNKNOWN';
}
const bad = /GPL|AGPL|LGPL|SSPL|UNKNOWN|non-?commercial|no-?deriv/i;

function findLicenseFiles(dir) {
  if (!dir || !existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => /^(licen[sc]e|copying|notice|unlicense)/i.test(f))
    .map((f) => join(dir, f));
}
function copyrightLines(text) {
  return [
    ...new Set(
      text
        .split(/\r?\n/)
        .map((l) => l.trim().replace(/^[*#>\s]+/, ''))
        .filter((l) => /^(copyright|\(c\)|©)\s*(\(c\)|©)?\s*(\d|by\b)/i.test(l) && l.length < 200),
    ),
  ];
}

const texts = new Map(); // normalized body -> {id, text, by}
function collect(name, ver, dir, declared) {
  const files = findLicenseFiles(dir);
  let id = declared || 'UNKNOWN';
  const notices = [];
  let copy = [];
  for (const f of files) {
    const text = readFileSync(f, 'utf8');
    if (/notice/i.test(f.split(/[\\/]/).pop())) {
      notices.push(text.trim());
      continue;
    }
    id = detect(text, declared);
    copy = copy.concat(copyrightLines(text));
    // Some font packages (Source Sans/Serif/Code Pro) only name the holder on line 1.
    if (!copy.length && id === 'OFL-1.1') copy = [text.split(/\r?\n/)[0].trim()];
    const body = text
      .split(/\r?\n/)
      .filter((l) => !/^\s*(copyright|\(c\))/i.test(l))
      .join('\n')
      .replace(/\s+/g, ' ')
      .trim();
    if (!texts.has(body)) texts.set(body, { id, text: text.trim(), by: [name] });
    else texts.get(body).by.push(name);
  }
  if (declared && / OR /.test(declared)) id = declared; // SPDX expression, e.g. dompurify
  if (bad.test(id) || files.length === 0) flagged.push(`${name}@${ver}: ${id}${files.length ? '' : ' (no license file)'}`);
  return { name, ver, id, copy: [...new Set(copy)], notices };
}

// Go: only modules that actually link into the binary.
const goOut = execFileSync(
  'go',
  ['list', '-deps', '-f', '{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}', './cmd/kipple'],
  { cwd: root, encoding: 'utf8' },
);
const goMods = new Map();
for (const line of goOut.split('\n').filter(Boolean)) {
  const [p, v, d] = line.trim().split('|');
  if (v) goMods.set(p, { p, v, d });
}
const go = [...goMods.values()].sort((a, b) => a.p.localeCompare(b.p)).map((m) => collect(m.p, m.v, m.d));

// npm: production dependency closure from the lockfile.
const lock = JSON.parse(readFileSync(join(root, 'web/package-lock.json'), 'utf8'));
const npm = [];
for (const [path, info] of Object.entries(lock.packages)) {
  if (!path || info.dev || info.devOptional) continue;
  const dir = join(root, 'web', path);
  const pj = existsSync(join(dir, 'package.json')) ? JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) : {};
  const name = path.replace(/^.*node_modules\//, '');
  const declared = typeof pj.license === 'string' ? pj.license : pj.license?.type || info.license;
  npm.push(collect(name, info.version, dir, declared));
}
npm.sort((a, b) => a.name.localeCompare(b.name));
const fonts = npm.filter((p) => p.name.startsWith('@fontsource'));
const nonFonts = npm.filter((p) => !p.name.startsWith('@fontsource'));

const OFL = [...texts.values()].find((t) => t.id === 'OFL-1.1');
let out = `# Third-party notices

Generated by \`scripts/gen-notices.mjs\`; do not edit by hand. Kipple itself is under the
PolyForm Noncommercial License 1.0.0 (see LICENSE). The components below are redistributed
under their own licenses.

## Bundled fonts

Self-hosted from the \`@fontsource\` packages and included in the web build. Each family is
licensed under the SIL Open Font License 1.1 (text below) unless the table says otherwise.
Charter is not bundled; it is used only when the operating system provides it.

| Family package | Version | License | Copyright |
|---|---|---|---|
${fonts.map((f) => `| ${f.name} | ${f.ver} | ${f.id} | ${f.copy.join('; ').replace(/\|/g, '/') || 'see package'} |`).join('\n')}

Reserved Font Names, where declared in the copyright lines of the OFL text below, apply to the
original font software. The fonts are redistributed unmodified apart from Fontsource packaging.

${OFL ? '```\n' + OFL.text + '\n```' : '(OFL text not found in packages)'}

## Go dependencies (linked into the binary)

| Module | Version | License |
|---|---|---|
${go.map((m) => `| ${m.name} | ${m.ver} | ${m.id} |`).join('\n')}

## npm production dependencies

| Package | Version | License |
|---|---|---|
${nonFonts.map((m) => `| ${m.name} | ${m.ver} | ${m.id} |`).join('\n')}

## Copyright notices

${[...go, ...nonFonts]
  .filter((m) => m.copy.length)
  .map((m) => `- **${m.name}** ${m.ver}: ${m.copy.join('; ')}`)
  .join('\n')}
`;
const withNotices = [...go, ...npm].filter((m) => m.notices.length);
if (withNotices.length) {
  out += '\n## NOTICE files\n\n' + withNotices.map((m) => `### ${m.name}\n\n\`\`\`\n${m.notices.join('\n\n')}\n\`\`\`\n`).join('\n');
}
out += '\n## License texts\n\nOne copy of each distinct license text, with the packages that use it.\n\n';
for (const t of texts.values()) {
  if (t.id === 'OFL-1.1') continue;
  out += `### ${t.id}\n\nUsed by: ${[...new Set(t.by)].join(', ')}\n\n\`\`\`\n${t.text}\n\`\`\`\n\n`;
}
writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), out);
console.error(`wrote THIRD_PARTY_NOTICES.md: ${go.length} Go modules, ${npm.length} npm packages`);
if (flagged.length) console.error('FLAGGED:\n  ' + flagged.join('\n  '));
